### ISSUE TITLE
Remaining issues in TYPO3 13

### ISSUE THREAD

**Issue by maelstromer** [jweiland-net/pforum#27]
Greetings,

unfortunately, I have encountered some severe issues under TYPO3 13, which still make this extension unusable in its current form.

Even though I disabled the "auth" setting in Typoscript, the extension still calls FrontedGroupHelper->getGroupUidsOfCurrentUser() when trying to access any of the forums I created. This class contains a breaking bug in line 32:

`$groupUids = $this->getTypoScriptFrontendController()->fe_user->groupData['uid'];`

Here, you are trying to access the fe_user array from TSFE. However, this array was removed with TYPO3 13, as is documented here: 
https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/AppendixA/Index.html#appendix-include-tsfe-feuser

Hence, I am getting the following error:

<img width="1141" height="433" alt="Image" src="https://github.com/user-attachments/assets/97b3e7eb-d29e-499a-8134-6ed695d0542d" />

This part needs migration, the necessary steps for that should be explained in the link I provided.

Another issue I found is that the backend module does not seem to load. When trying to access it it throws the following error:

<img width="1139" height="400" alt="Image" src="https://github.com/user-attachments/assets/3f59e2f2-f8cd-4788-80e3-face79a50a0d" />

I have not looked further into this, as this is currently of secondary concern for our client and I already spent too much time on this.

Hopefully, we can find a way to resolve this issue.

**Comment by hojalatheef** [comment]
Hi @maelstromer ,

Thank you for your detailed feedback and for pointing out the issues you’ve encountered.
You are correct, there were multiple issues related to backend modules and TYPO3 v13 compatibility. These have been addressed with the release of version 6.0.1 of the extension.

Please update to the latest version and check if the problems persist.
If you continue to experience issues after the update, please share the details so we can investigate further.

Thanks again for your patience and support.

Best regards,
Hoja

**Comment by maelstromer** [comment]
Hey Hoja,

your welcome! I am glad to see that this issue is being addressed so swiftly and the backend module is also working correctly now. 

However, this was only of secondary concern for us, currently. Out primary concern is the first point I mentioned and provided details about: The forum CE does not work because of the use of the removed 'fe_user' property in FrontendGroupHelper, which throws an error in the frontend. 
As this property is still being used in the class in question, our problems unfortunately persist.

I hope you will find a way to fix this issue as swiftly as the last one.

Best regards,
Marc

**Comment by Oktopuce** [comment]
You make a new version 6.2.4 but still not working with TYPO3 V13.

This exception is still there : 

>  (1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
> 
> PHP Warning: Undefined property: TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::$fe_user in /app/vendor/jweiland/pforum/Classes/Controller/TopicController.php line 261
> 

I don't understand why you don't apply the patch with PR https://github.com/jweiland-net/pforum/pull/30

**Comment by sfroemkenjw** [comment]
I don't check issues and PRs on a fixed schedule, I only get to them when a task brings me back in. The frustration here is understandable and justified.

Version 7 went out last week because a customer had a problem with file uploads in this extension. While fixing that I also merged a PR that resolves the TSFE issue reported in this ticket. Version 7 remains fully compatible with TYPO3 13.

If you upgrade, also update checkfaluploads to its latest version, since that fix and this one belong together.

Thanks to everyone who kept flagging this, it helped get it resolved.
